logging:
  path: /data/log/leisure-backend-gateway

server:
  servlet:
    context-path: /

spring:
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  eureka:
    enabled: false

zuul:
  SendErrorFilter:
    error:
      disable: true
      
  routes:
    authentication-api:
      path: /authentication/**
      stripPrefix: true
      url: forward:/

authentication:
  non-require:
    uris: /authentication/**,/**/**swagger**/**,/**/v2/api-docs

access:
  logger:
    exclude:
      uris: /**/favicon.ico,/**/swagger**/**,/**/health/**,/**/webjars/**
