logging:
  path: /data/log/leisure-backend-gateway

server:
  servlet:
    context-path: /

spring:
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true

ribbon:
  connectTimeout: 3000
  readTimeout: 60000
  eureka:
    enabled: false

zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    api:
      path: /**
      stripPrefix: false
      url: forward:/
    authentication:
      path: /authorization/sign-in/**
      stripPrefix: true
      url: forward:/sign-in


uris:
  non-authentication: /authorization/sign-in/**,/**/**swagger**/**,/**/v2/api-docs
  deny: /sign-in/**

access:
  logger:
    exclude:
      uris: /**/favicon.ico,/**/swagger**/**,/**/health/**,/**/webjars/**
