warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2

leisure-member:
  ribbon:
    listOfServers: http://172.31.212.8:10002

leisure-member-api:
  ribbon:
    listOfServers: http://172.31.212.8:10001

spring:
  redis:
    host: 172.31.212.8
    port: 16379
    database: 0
  rabbitmq:
    addresses: 47.101.155.253
    port: 5672
    username: leisure
    password: leisure
    publisher-confirms: true
    publisher-returns: true

zuul:
  routes:
    leisure-member-api:
      serviceId: leisure-member-api
      path: /leisure-member-api/**
      stripPrefix: false