logging:
  path: /data/log/leisure-backend-gateway

server:
  servlet:
    context-path: /leisure-backend-gateway

warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2



url:
  leisure-member: http://47.105.97.16:8080/leisure-member