logging:
  path: /data/log/leisure-backend-gateway

server:
  servlet:
    context-path: /

zuul:
  SendErrorFilter:
    error:
      disable: true

ribbon:
  eureka:
    enabled: false

access:
  logger:
    exclude:
      uris: /**/favicon.ico,/**/swagger**/**,/**/health/**,/**/webjars/**