leisure-member:
  ribbon:
    listOfServers: http://127.0.0.1:10002
    ReadTimeout: 5000
    ConnectTimeout: 5000

leisure-member-api:
  ribbon:
    listOfServers: http://127.0.0.1:10001
    ReadTimeout: 5000
    ConnectTimeout: 5000
spring:
  redis:
    host: 47.105.97.16
    port: 16379
    database: 0
  rabbitmq:
    addresses: 47.101.155.253
    port: 5672
    username: leisure
    password: leisure

zuul:
  routes:
    leisure-member-api:
      serviceId: leisure-member-api
      path: /leisure-member-api/**
      stripPrefix: false